Repository woowa-techcamp-2022/android-banchan-02, pull requests merged in 2022-08, with the labels that each got.

#8 [FEAT] 리사이클러뷰 세로 아이템 UI 구현, fake data로 리사이클러뷰 구현
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/banchan/MainActivity.kt
  app/src/main/java/com/example/banchan/MockData.kt
  app/src/main/java/com/example/banchan/data/response/ItemModel.kt
  app/src/main/java/com/example/banchan/ui/MainActivity.kt
  app/src/main/java/com/example/banchan/ui/adapter/MenuAdapter.kt
  app/src/main/java/com/example/banchan/ui/adapter/MenuViewHolder.kt
  app/src/main/java/com/example/banchan/util/ext/BindingAdapters.kt
  app/src/main/res/drawable/background_line.xml
  app/src/main/res/drawable/ic_circle_checked.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_menu.xml
  app/src/main/res/values/themes.xml
Labels: feature

#19 [FEAT] 스피너 구현, 메인 필터링 기능 구현 #16
  .idea/misc.xml
  app/src/main/java/com/example/banchan/domain/model/ItemModel.kt
  app/src/main/java/com/example/banchan/presentation/custom/FilterAdapter.kt
  app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookViewModel.kt
  app/src/main/java/com/example/banchan/presentation/home/maincook/adapter/MainAdapter.kt
  app/src/main/java/com/example/banchan/presentation/home/maincook/adapter/MainFilterViewHolder.kt
  app/src/main/java/com/example/banchan/util/ext/StrExt.kt
  app/src/main/res/layout/item_menu_filter.xml
  app/src/main/res/layout/menu_filter.xml
  app/src/main/res/values/array.xml
Labels: feature

#21 [FEAT] 국물 요리 화면 UI, 로직 구현 #20
  .idea/misc.xml
  app/src/main/java/com/example/banchan/data/response/soup/SoupResponse.kt
  app/src/main/java/com/example/banchan/domain/usecase/GetSoupDishesUseCase.kt
  app/src/main/java/com/example/banchan/presentation/home/soup/SoupFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/soup/SoupViewModel.kt
  app/src/main/java/com/example/banchan/presentation/home/soup/adapter/SoupAdapter.kt
  app/src/main/java/com/example/banchan/presentation/home/soup/adapter/TotalFilterViewViewHolder.kt
  app/src/main/res/layout/fragment_soup.xml
  app/src/main/res/layout/total_filter.xml
  app/src/main/res/values/strings.xml
Labels: feature

#27 [FEAT] 메인, 국물, 반찬 리스트 헤더, 로드 상태 화면 구현 #26
  app/src/main/java/com/example/banchan/domain/model/BestListItem.kt
  app/src/main/java/com/example/banchan/domain/model/ItemModel.kt
  app/src/main/java/com/example/banchan/presentation/adapter/best/BestListAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/home/CommonAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/home/HomeEmptyViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/home/HomeErrorViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/home/HomeHeaderViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/home/HomeLoadingViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/main/CommonSpacingItemDecorator.kt
  app/src/main/java/com/example/banchan/presentation/adapter/main/GridSpacingItemDecorator.kt
  app/src/main/java/com/example/banchan/presentation/adapter/main/MainAdapter.kt
  app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookViewModel.kt
  app/src/main/java/com/example/banchan/presentation/home/side/SideFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/side/SideViewModel.kt
  app/src/main/java/com/example/banchan/presentation/home/soup/SoupFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/soup/SoupViewModel.kt
  app/src/main/res/layout/fragment_main_cook.xml
  app/src/main/res/layout/fragment_side.xml
  app/src/main/res/layout/fragment_soup.xml
Labels: feature

#30 [FEAT] 장바구니 DB 구현, 쿼리 추가 #29
  app/build.gradle
  app/src/main/java/com/example/banchan/data/repository/BasketRepository.kt
  app/src/main/java/com/example/banchan/data/repository/BasketRepositoryImpl.kt
  app/src/main/java/com/example/banchan/data/source/BanChanDataSource.kt
  app/src/main/java/com/example/banchan/data/source/BasketDataSource.kt
  app/src/main/java/com/example/banchan/data/source/local/BanChanDatabase.kt
  app/src/main/java/com/example/banchan/data/source/local/BasketDao.kt
  app/src/main/java/com/example/banchan/data/source/local/BasketItem.kt
  app/src/main/java/com/example/banchan/data/source/local/BasketLocalDataSource.kt
  app/src/main/java/com/example/banchan/data/source/remote/BanChanRemoteDataSource.kt
  app/src/main/java/com/example/banchan/di/DataSourceModule.kt
  app/src/main/java/com/example/banchan/di/DatabaseModule.kt
  app/src/main/java/com/example/banchan/di/RepositoryModule.kt
Labels: feature

#36 [FEAT] 최근 상품 DB 구현, datasource, repository 구현 #35
  app/src/main/java/com/example/banchan/data/Converter.kt
  app/src/main/java/com/example/banchan/data/repository/BanChanRepositoryImpl.kt
  app/src/main/java/com/example/banchan/data/repository/BasketRepository.kt
  app/src/main/java/com/example/banchan/data/repository/BasketRepositoryImpl.kt
  app/src/main/java/com/example/banchan/data/repository/RecentlyProductRepository.kt
  app/src/main/java/com/example/banchan/data/repository/RecentlyProductRepositoryImpl.kt
  app/src/main/java/com/example/banchan/data/source/BasketDataSource.kt
  app/src/main/java/com/example/banchan/data/source/RecentlyProductDataSource.kt
  app/src/main/java/com/example/banchan/data/source/local/BanChanDatabase.kt
  app/src/main/java/com/example/banchan/data/source/local/basket/BasketDao.kt
  app/src/main/java/com/example/banchan/data/source/local/basket/BasketItem.kt
  app/src/main/java/com/example/banchan/data/source/local/basket/BasketLocalDataSource.kt
  app/src/main/java/com/example/banchan/data/source/local/recent/RecentlyProduct.kt
  app/src/main/java/com/example/banchan/data/source/local/recent/RecentlyProductDao.kt
  app/src/main/java/com/example/banchan/data/source/local/recent/RecentlyProductLocalDataSource.kt
  app/src/main/java/com/example/banchan/di/DataSourceModule.kt
  app/src/main/java/com/example/banchan/di/DatabaseModule.kt
  app/src/main/java/com/example/banchan/di/RepositoryModule.kt
Labels: feature

#38 [FEAT] 내역 DB 구현, datasource, repository 구현 #37
  app/src/main/java/com/example/banchan/data/repository/HistoryRepository.kt
  app/src/main/java/com/example/banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/main/java/com/example/banchan/data/source/HistoryDataSource.kt
  app/src/main/java/com/example/banchan/data/source/local/BanChanDatabase.kt
  app/src/main/java/com/example/banchan/data/source/local/history/History.kt
  app/src/main/java/com/example/banchan/data/source/local/history/HistoryDao.kt
  app/src/main/java/com/example/banchan/data/source/local/history/HistoryItem.kt
  app/src/main/java/com/example/banchan/data/source/local/history/HistoryLocalDataSource.kt
  app/src/main/java/com/example/banchan/di/DataSourceModule.kt
  app/src/main/java/com/example/banchan/di/DatabaseModule.kt
  app/src/main/java/com/example/banchan/di/RepositoryModule.kt
  app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookViewModel.kt
Labels: feature

#43 [FEAT] 내역 쿼리 수정 #42
  app/src/main/java/com/example/banchan/data/repository/HistoryRepository.kt
  app/src/main/java/com/example/banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/main/java/com/example/banchan/data/source/HistoryDataSource.kt
  app/src/main/java/com/example/banchan/data/source/local/history/HistoryDao.kt
  app/src/main/java/com/example/banchan/data/source/local/history/HistoryItem.kt
  app/src/main/java/com/example/banchan/data/source/local/history/HistoryLocalDataSource.kt
  app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookViewModel.kt
Labels: feature

#47 [FEAT] 주문 상태 화면 UI 및 로직 일부 구현 #46
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/banchan/BanChanApp.kt
  app/src/main/java/com/example/banchan/OrderService.kt
  app/src/main/java/com/example/banchan/data/repository/HistoryRepository.kt
  app/src/main/java/com/example/banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/main/java/com/example/banchan/data/source/HistoryDataSource.kt
  app/src/main/java/com/example/banchan/data/source/local/history/History.kt
  app/src/main/java/com/example/banchan/data/source/local/history/HistoryDao.kt
  app/src/main/java/com/example/banchan/data/source/local/history/HistoryLocalDataSource.kt
  app/src/main/java/com/example/banchan/domain/usecase/GetHistoryByIdUseCase.kt
  app/src/main/java/com/example/banchan/domain/usecase/UpdateHistoryUseCase.kt
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonFilterViewViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonOrderFooterAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonOrderFooterViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonOrderHeaderAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonOrderHeaderViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/ordersuccess/OrderSuccessItemAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/ordersuccess/OrderSuccessItemViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/home/side/SideFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/side/SideViewModel.kt
  app/src/main/java/com/example/banchan/presentation/home/soup/SoupFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/soup/SoupViewModel.kt
  app/src/main/java/com/example/banchan/presentation/main/MainActivity.kt
  app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessFragment.kt
  app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessViewModel.kt
  app/src/main/java/com/example/banchan/util/Constant.kt
  app/src/main/res/layout/fragment_order_success.xml
  app/src/main/res/layout/item_menu.xml
  app/src/main/res/layout/item_menu_large.xml
  app/src/main/res/layout/item_menu_medium.xml
  app/src/main/res/layout/item_order_footer.xml
  app/src/main/res/layout/item_order_header.xml
  app/src/main/res/layout/item_order_success.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#56 [FIX] 장바구니, 최근 본 상품 아이템에 title 함께 저장하도록 수정 #55
  app/src/main/java/com/example/banchan/OrderService.kt
  app/src/main/java/com/example/banchan/data/repository/HistoryRepository.kt
  app/src/main/java/com/example/banchan/data/source/local/basket/BasketItem.kt
  app/src/main/java/com/example/banchan/data/source/local/recent/RecentlyProduct.kt
  app/src/main/java/com/example/banchan/domain/usecase/history/GetHistoryByIdUseCase.kt
  app/src/main/java/com/example/banchan/domain/usecase/history/UpdateHistoryUseCase.kt
  app/src/main/java/com/example/banchan/domain/usecase/recently/InsertRecentlyItemUseCase.kt
  app/src/main/java/com/example/banchan/domain/usecase/recently/SaveRecentProduct.kt
  app/src/main/java/com/example/banchan/presentation/main/BasketViewModel.kt
  app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessViewModel.kt
  app/src/main/java/com/example/banchan/presentation/productdetail/ProductDetailViewModel.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt
Labels: fix

#60 [FEAT] 최근 본 상품 목록 구현 #52
  .idea/misc.xml
  app/src/main/java/com/example/banchan/data/response/best/Item.kt
  app/src/main/java/com/example/banchan/data/response/detail/DetailResponse.kt
  app/src/main/java/com/example/banchan/domain/model/RecentlyProductModel.kt
  app/src/main/java/com/example/banchan/domain/usecase/recently/GetRecentProductUseCase.kt
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonGridSpacingItemDecorator.kt
  app/src/main/java/com/example/banchan/presentation/adapter/recentlyproduct/RecentlyProductAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/recentlyproduct/RecentlyProductViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/banchan/presentation/main/MainActivity.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductViewModel.kt
  app/src/main/java/com/example/banchan/util/ext/TimeExt.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_recently_product.xml
  app/src/main/res/layout/item_recent.xml
Labels: feature

#64 [FEAT] 커스텀 수량 조절 UI 사이즈 attr 추가 #63
  .idea/misc.xml
  app/src/main/java/com/example/banchan/presentation/custom/AmountCounter.kt
  app/src/main/res/layout/amount_counter.xml
  app/src/main/res/values/attrs.xml
Labels: feature

#62 [FIX] 스크롤 초기화 버그 수정 #61
  app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookViewModel.kt
Labels: bug

#69 [FEAT] 버튼 연결 및 리팩토링 #68
  .idea/misc.xml
  app/src/main/java/com/example/banchan/data/response/detail/DetailResponse.kt
  app/src/main/java/com/example/banchan/domain/model/RecentlyProductItemModel.kt
  app/src/main/java/com/example/banchan/domain/usecase/recently/GetRecentlyItemUseCase.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyItemAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyItemHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyTabAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyTabHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketTabAdapter.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketViewModel.kt
  app/src/main/java/com/example/banchan/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/banchan/presentation/productdetail/ProductDetailFragment.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductViewModel.kt
  app/src/main/res/layout/item_basket_recently_product.xml
  app/src/main/res/layout/item_basket_recently_tab.xml
Labels: feature

#67 [FEAT] 장바구니 수량 증가, 감소 구현 및 합계 금액 로직 구현
  app/src/main/java/com/example/banchan/domain/model/OrderModel.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketItemViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketListAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketOrderAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketOrderViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketViewModel.kt
  app/src/main/res/layout/item_basket_order.xml
  app/src/main/res/values/strings.xml
Labels: feature

#71 [FIX] UI 버그 수정 #70
  .idea/misc.xml
  app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookFragment.kt
  app/src/main/res/layout/amount_counter.xml
  app/src/main/res/layout/item_basket.xml
Labels: bug

#79 [FEAT] 배송 완료 notification 구현 #78
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/banchan/AlarmReceiver.kt
  app/src/main/java/com/example/banchan/OrderService.kt
  app/src/main/java/com/example/banchan/data/source/local/history/History.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
  app/src/main/java/com/example/banchan/presentation/main/MainActivity.kt
  app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessFragment.kt
  app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessViewModel.kt
  app/src/main/java/com/example/banchan/util/Constant.kt
  app/src/main/res/values/strings.xml
Labels: feature

#83 [FEAT] 주문 완료 누르면 주문 상태 화면으로 이동 #81
  app/src/main/java/com/example/banchan/OrderService.kt
  app/src/main/java/com/example/banchan/data/repository/HistoryRepository.kt
  app/src/main/java/com/example/banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/main/java/com/example/banchan/data/source/HistoryDataSource.kt
  app/src/main/java/com/example/banchan/data/source/local/history/HistoryDao.kt
  app/src/main/java/com/example/banchan/data/source/local/history/HistoryLocalDataSource.kt
  app/src/main/java/com/example/banchan/domain/usecase/history/GetHistoryByIdUseCase.kt
  app/src/main/java/com/example/banchan/domain/usecase/history/InsertHistoryItemsUseCase.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketViewModel.kt
  app/src/main/java/com/example/banchan/presentation/main/MainActivity.kt
  app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessFragment.kt
  app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessViewModel.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt
Labels: feature

#88 [FEAT] 최근 목록 클릭시 장바구니, 상세 화면으로 가도록 구현, 최근 목록 시간순 정렬 #87, #80
  app/src/main/java/com/example/banchan/data/response/best/Item.kt
  app/src/main/java/com/example/banchan/data/response/detail/DetailResponse.kt
  app/src/main/java/com/example/banchan/domain/model/ItemModel.kt
  app/src/main/java/com/example/banchan/domain/model/RecentlyProductModel.kt
  app/src/main/java/com/example/banchan/domain/usecase/recently/GetRecentProductUseCase.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyItemHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyListAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyTabAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyTabHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/recentlyproduct/RecentlyProductAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/recentlyproduct/RecentlyProductViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketViewModel.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt
  app/src/main/res/layout/item_basket_recently_product.xml
  app/src/main/res/layout/item_recent.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature

#91 [REFACTOR] 히스토리 업데이트하는 방식 변경 #89
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/banchan/AlarmReceiver.kt
  app/src/main/java/com/example/banchan/BanChanApp.kt
  app/src/main/java/com/example/banchan/OrderService.kt
  app/src/main/java/com/example/banchan/OrderWorker.kt
  app/src/main/java/com/example/banchan/data/repository/HistoryRepository.kt
  app/src/main/java/com/example/banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/main/java/com/example/banchan/data/source/HistoryDataSource.kt
  app/src/main/java/com/example/banchan/data/source/local/history/History.kt
  app/src/main/java/com/example/banchan/data/source/local/history/HistoryDao.kt
  app/src/main/java/com/example/banchan/data/source/local/history/HistoryLocalDataSource.kt
  app/src/main/java/com/example/banchan/domain/usecase/history/UpdateHistoryUseCase.kt
  app/src/main/java/com/example/banchan/domain/usecase/recently/GetRecentProductUseCase.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
  app/src/main/java/com/example/banchan/presentation/orderlist/OrderListViewModel.kt
  app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessViewModel.kt
Labels: refactor

#98 [FEAT] 앱바 사용자프로필 업데이트 #97
  app/src/main/java/com/example/banchan/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/OrderStateViewModel.kt
  app/src/main/java/com/example/banchan/presentation/orderlist/OrderListFragment.kt
Labels: feature, PairProgramming

#103 [REFACTOR] UiState Class 생성
  app/src/main/java/com/example/banchan/presentation/UiState.kt
Labels: refactor, PairProgramming

#95 [TEST] 최근 상품 테스트 코드 작성 #92
  app/build.gradle
  app/src/test/java/com/example/banchan/MainCoroutineRule.kt
  app/src/test/java/com/example/banchan/data/RecentProductFakeDataSource.kt
  app/src/test/java/com/example/banchan/data/RecentProductRepositoryImplTest.kt
Labels: test

#107 [REFACTOR] 국물, 밑반찬 요리 리팩토링(ConcatAdapter 사용, UiState 관리, 리로드 구현) #106
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonFilterAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/home/HomeHeaderAdapter.kt
  app/src/main/java/com/example/banchan/presentation/home/maindish/MainDishFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/side/SideFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/side/SideViewModel.kt
  app/src/main/java/com/example/banchan/presentation/home/soup/SoupFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/soup/SoupViewModel.kt
  app/src/main/res/layout/fragment_side.xml
  app/src/main/res/layout/fragment_soup.xml
Labels: refactor

#112 [REFACTOR] 프래그먼트 화면 이동 로직 개선 #109
  .idea/misc.xml
  app/src/main/java/com/example/banchan/domain/usecase/recently/GetRecentProductUseCase.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyItemHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyListAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyTabAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyTabHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/orderlist/OrderListAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/orderlist/OrderListViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketListViewModel.kt
  app/src/main/java/com/example/banchan/presentation/dialog/BasketCheckDialog.kt
  app/src/main/java/com/example/banchan/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/HomeTabFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/OrderStateViewModel.kt
  app/src/main/java/com/example/banchan/presentation/home/best/BestFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/side/SideFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/soup/SoupFragment.kt
  app/src/main/java/com/example/banchan/presentation/main/FragmentType.kt
  app/src/main/java/com/example/banchan/presentation/main/MainActivity.kt
  app/src/main/java/com/example/banchan/presentation/main/MainViewModel.kt
  app/src/main/java/com/example/banchan/presentation/orderlist/OrderListFragment.kt
  app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessFragment.kt
  app/src/main/java/com/example/banchan/presentation/productdetail/ProductDetailFragment.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductViewModel.kt
  app/src/main/java/com/example/banchan/util/ext/BindingAdapters.kt
  app/src/main/res/drawable/placeholder.png
Labels: refactor

#114 [FIX] 스피너 아이콘 방향 수정 #110
  .idea/misc.xml
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonFilterViewViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/custom/CustomSpinner.kt
  app/src/main/java/com/example/banchan/presentation/custom/FilterAdapter.kt
  app/src/main/java/com/example/banchan/presentation/main/MainActivity.kt
  app/src/main/res/drawable/spinner_check.xml
  app/src/main/res/drawable/spinner_close.xml
  app/src/main/res/drawable/spinner_open.xml
  app/src/main/res/layout/menu_filter.xml
Labels: feature

#116 [REFACTOR] UiState DataBinding 적용
  app/src/main/java/com/example/banchan/presentation/home/maindish/MainDishFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/side/SideFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/soup/SoupFragment.kt
  app/src/main/java/com/example/banchan/util/ext/BindingAdapters.kt
  app/src/main/res/layout/fragment_main_dish.xml
  app/src/main/res/layout/fragment_side.xml
  app/src/main/res/layout/fragment_soup.xml
  app/src/main/res/layout/item_home_empty.xml
  app/src/main/res/layout/item_home_error.xml
Labels: refactor

#117 [REFACTOR] 기획전 탭 ConcatAdapter 적용
  app/src/main/java/com/example/banchan/presentation/RecylerItemTouchInterceptorListener.kt
  app/src/main/java/com/example/banchan/presentation/adapter/best/BestItemAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/best/BestItemViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/best/BestListAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/best/BestWrapAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/best/BestWrapViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/home/best/BestFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/best/BestViewModel.kt
  app/src/main/res/layout/fragment_best.xml
  app/src/main/res/layout/item_best_list.xml
Labels: refactor

#120 [REFACTOR] 주문 상태 화면 UiState 관리 #119
  .idea/misc.xml
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonOrderFooterAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonOrderFooterViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonOrderHeaderAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonOrderHeaderViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/ordersuccess/OrderSuccessItemAdapter.kt
  app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessFragment.kt
  app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessViewModel.kt
  app/src/main/res/layout/fragment_order_success.xml
  app/src/main/res/layout/item_order_header.xml
Labels: refactor

#128 [FEAT] notification 누르면 OrderSuccess 화면으로 이동하도록 구현 #111
  app/src/main/java/com/example/banchan/AlarmReceiver.kt
  app/src/main/java/com/example/banchan/presentation/main/MainActivity.kt
Labels: feature

#124 [FEAT] 네트워크 체크 #96
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/banchan/presentation/main/MainActivity.kt
  app/src/main/java/com/example/banchan/util/NetworkConnectManager.kt
  app/src/main/res/values/strings.xml
Labels: feature, PairProgramming

#126 [REFACTOR] #121 - 제품 디테일 화면 UiState 적용
  app/src/main/java/com/example/banchan/presentation/productdetail/ProductDetailFragment.kt
  app/src/main/java/com/example/banchan/presentation/productdetail/ProductDetailViewModel.kt
  app/src/main/res/layout/fragment_product_detail.xml
Labels: refactor

#125 [REFACTOR] 최근 본 상품 UiState 관리 #123
  .idea/misc.xml
  app/src/main/java/com/example/banchan/domain/usecase/recently/GetRecentProductUseCase.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductViewModel.kt
  app/src/main/java/com/example/banchan/util/ext/BindingAdapters.kt
  app/src/main/res/layout/fragment_recently_product.xml
Labels: refactor

#133 [FEAT] 최근 본 상품 화면 페이징 적용 #132
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/banchan/data/repository/RecentlyProductRepository.kt
  app/src/main/java/com/example/banchan/data/repository/RecentlyProductRepositoryImpl.kt
  app/src/main/java/com/example/banchan/data/source/RecentlyProductDataSource.kt
  app/src/main/java/com/example/banchan/data/source/local/recent/RecentlyProductDao.kt
  app/src/main/java/com/example/banchan/data/source/local/recent/RecentlyProductLocalDataSource.kt
  app/src/main/java/com/example/banchan/domain/usecase/recently/GetRecentProductPagingUseCase.kt
  app/src/main/java/com/example/banchan/domain/usecase/recently/GetRecentProductUseCase.kt
  app/src/main/java/com/example/banchan/presentation/adapter/recentlyproduct/RecentlyProductPagingAdapter.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketListViewModel.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketRecentlyProductViewModel.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductViewModel.kt
  app/src/main/java/com/example/banchan/util/ext/BindingAdapters.kt
  app/src/main/res/layout/fragment_recently_product.xml
  app/src/main/res/layout/layout_recent_empty.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/example/banchan/data/RecentProductFakeDataSource.kt
Labels: feature

#130 [FIX] 버그 수정 #129
  app/src/main/java/com/example/banchan/presentation/adapter/common/CommonAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/main/LargeMenuViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/main/MainFilterViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/main/MainItemAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/main/MediumMenuViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
  app/src/main/java/com/example/banchan/presentation/custom/AmountCounter.kt
  app/src/main/java/com/example/banchan/presentation/dialog/BasketBottomSheet.kt
  app/src/main/java/com/example/banchan/presentation/home/maindish/MainDishViewModel.kt
  app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessViewModel.kt
  app/src/main/java/com/example/banchan/presentation/productdetail/ProductDetailFragment.kt
  app/src/main/java/com/example/banchan/util/ext/BindingAdapters.kt
  app/src/main/res/drawable/grid_type_check.xml
  app/src/main/res/drawable/grid_type_uncheck.xml
  app/src/main/res/drawable/linear_type_check.xml
  app/src/main/res/drawable/linear_type_uncheck.xml
  app/src/main/res/layout/amount_counter.xml
  app/src/main/res/layout/item_basket_tab.xml
  app/src/main/res/layout/item_order_list.xml
  app/src/main/res/layout/menu_filter.xml
  app/src/main/res/layout/total_filter.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/attrs.xml
Labels: bug, PairProgramming

#134 [REFACTOR] 장바구니 화면 UiState 적용
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketEmptyAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketEmptyViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketErrorAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketErrorViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketLoadingAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketLoadingViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyListAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyTabAdapter.kt
  app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketRecentlyTabHolder.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketListViewModel.kt
  app/src/main/res/drawable/empty_cart.png
  app/src/main/res/drawable/none_recently_product.png
  app/src/main/res/layout/item_basket_empty.xml
  app/src/main/res/layout/item_basket_error.xml
  app/src/main/res/layout/item_basket_loading.xml
  app/src/main/res/layout/item_basket_recently_tab.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#136 [REFACTOR] 주문 목록 UiState 적용
  .idea/misc.xml
  app/src/main/java/com/example/banchan/presentation/home/OrderStateViewModel.kt
  app/src/main/java/com/example/banchan/presentation/orderlist/OrderListFragment.kt
  app/src/main/res/drawable/empty_order.png
  app/src/main/res/layout/fragment_order_list.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#139 [FIX] 어댑터 lateinit으로 수정 #135
  app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/best/BestFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/maindish/MainDishFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/side/SideFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/soup/SoupFragment.kt
  app/src/main/java/com/example/banchan/presentation/orderlist/OrderListFragment.kt
  app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessFragment.kt
  app/src/main/java/com/example/banchan/presentation/productdetail/ProductDetailFragment.kt
  app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt
Labels: bug

#155 [FIX] 배송 상태 화면 바텀 padding 추가 #145
  app/src/main/res/layout/item_order_footer.xml
Labels: bug

#157 [FIX] spinner 오른쪽 맞춤, ui 세로 방향 center 맞춤 #152
  app/src/main/res/drawable/spinner_arrow.xml
  app/src/main/res/drawable/spinner_check.xml
  app/src/main/res/drawable/spinner_close.xml
  app/src/main/res/drawable/spinner_open.xml
  app/src/main/res/layout/menu_filter.xml
Labels: bug

#159 [FIX] 중복 주문 상태 프래그먼트 pop #144
  app/src/main/java/com/example/banchan/presentation/main/MainActivity.kt
Labels: bug

#154 [FIX] 레이아웃 타입 바뀌었을때 스크롤 위치 유지하도록 수정 #153
  app/src/main/java/com/example/banchan/presentation/home/maindish/MainDishFragment.kt
Labels: bug

#163 [REFACTOR] 장바구니 아이템 API 수집 속도 개선
  app/src/main/java/com/example/banchan/data/response/detail/DetailResponse.kt
  app/src/main/java/com/example/banchan/data/source/local/basket/BasketItem.kt
  app/src/main/java/com/example/banchan/domain/model/BasketModel.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
  app/src/main/java/com/example/banchan/presentation/basket/BasketListViewModel.kt
  app/src/main/java/com/example/banchan/presentation/dialog/AmountDialogViewModel.kt
Labels: refactor

#166 [FIX] #143 - 앱바의 메뉴 잘 눌리도록 개선 진행
  .idea/misc.xml
  app/src/main/res/layout/appbar_ordering.xml
Labels: fix

#168 [REFACTOR] 프로젝트 최종 리팩토링
  app/src/main/java/com/example/banchan/MockData.kt
  app/src/main/java/com/example/banchan/domain/model/BestListItem.kt
  app/src/main/java/com/example/banchan/domain/model/ResponseState.kt
  app/src/main/java/com/example/banchan/presentation/adapter/home/HomeEmptyViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/home/HomeErrorViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/adapter/home/HomeLoadingViewHolder.kt
  app/src/main/java/com/example/banchan/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/banchan/presentation/home/maindish/MainDishFragment.kt
  app/src/main/res/layout/fragment_main_dish.xml
Labels: refactor, PairProgramming
